services:
  devicemanager:
    build: 
      context: .
      dockerfile: Dockerfile
    network_mode: host
    ports:
      - "8089:8089"
    volumes:
      - ./config.json:/app/config.json:ro
    environment:
      - DEFAULT_CONFIG_PATH=/app/config.json
      - HTTP_PORT=8089